### ISSUE TITLE
msvc-tools and OCaml/OPAM

### ISSUE THREAD

**Issue by db4** [metastack/msvs-tools#2]
OPAM Makefile now has OCAML_PORT=msvc option that auto-detects Visual Studio and bootstrap working ((in theory) OCaml compiler. As an OCaml contributor, do you have any plans to integrate msvs-tools directly into OPAM and/or OCaml compiler build? So that one could write `./msvs-detect --arch=x86` somewhere in .comp compiler specification file and then do `opam switch` knowing that OPAM itself will set the necessary Visual Studio environment?

**Comment by dra27** [comment]
Yes, that's indeed planned (in fact, prototyped). With some additional changes based on https://github.com/ocaml/opam/pull/2930, you can say things like:

`opam switch 4.06.1-msvc64 ocaml-base-compiler.4.06.1 --arch=x86_64 --cc=cl`

from an empty command prompt, and opam automatically uses `msvs-detect` to set-up the Microsoft C Compiler environment. When you switch to that switch, it automatically includes it via a proposed `compiler` package (see https://github.com/dra27/opam-repository/commit/1ee610120e1ec727e42865d7e24b145e3ff786c6).

I demonstrated this at ICFP last year, but it's not in a particularly usable state at the moment, as I've been rebasing and upstreaming, but I'm hoping to have a demonstrable version of it again soon!

**Comment by db4** [comment]
I see. Thanks a lot for you work!
